# Generated by Django 4.0.2 on 2022-12-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default='')),
                ('state', models.IntegerField(default=0)),
                ('alarm', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('lux', models.IntegerField(default=0)),
                ('co2', models.IntegerField(default=0)),
                ('co', models.IntegerField(default=0)),
                ('gas', models.IntegerField(default=0)),
                ('movement', models.IntegerField(default=0)),
                ('door', models.IntegerField(default=0)),
            ],
        ),
    ]
