# Generated by Django 4.0.2 on 2022-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default=0, max_length=100)),
                ('alarm', models.CharField(default=0, max_length=100)),
                ('temperature', models.CharField(default=0, max_length=100)),
                ('humidity', models.CharField(default=0, max_length=100)),
                ('pressure', models.CharField(default=0, max_length=100)),
                ('lux', models.CharField(default=0, max_length=100)),
                ('co2', models.CharField(default=0, max_length=100)),
                ('co', models.CharField(default=0, max_length=100)),
                ('gas', models.CharField(default=0, max_length=100)),
                ('movement', models.CharField(default=0, max_length=100)),
                ('door', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
