# Generated by Django 4.0.4 on 2022-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('sensors', models.CharField(max_length=100)),
            ],
        ),
    ]
