# Generated by Django 4.1.5 on 2023-01-14 20:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
