# Generated by Django 4.0.2 on 2023-02-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_cabinet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='name',
        ),
    ]
