# Generated by Django 4.1.5 on 2023-01-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_cabinet_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='co',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='door',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='lux',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='number',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='time',
        ),
    ]
