# Generated by Django 4.0.2 on 2023-02-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_listcabinet_remove_cabinet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.listcabinet'),
        ),
    ]
