# Generated by Django 4.0.2 on 2023-02-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_cabinet_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcabinet',
            name='danger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listcabinet',
            name='number',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
